const data=getData(), selectedActivities=new Set();
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function wa(text){return `https://wa.me/${data.contact.whatsapp}?text=${encodeURIComponent(text)}`}
function render(){
  $("#roomGrid").innerHTML=data.rooms.filter(r=>r.available!==false).map(r=>`<article class="room-card"><img src="${r.image}" alt="${esc(r.name)}"><div class="room-body"><h3>${esc(r.name)}</h3><small>${esc(r.capacity)}</small><p>${esc(r.description)}</p><div class="tags">${r.amenities.map(a=>`<span class="tag">${esc(a)}</span>`).join("")}</div><div class="price"><div><strong>${formatINR(r.price)}</strong><small>/ night</small></div><button class="btn btn-primary room-book" data-id="${r.id}">Book This Room</button></div></div></article>`).join("");
  $("#activityGrid").innerHTML=data.activities.map(a=>`<article class="activity" data-id="${a.id}"><div class="icon">${a.icon}</div><h3>${esc(a.name)}</h3><p>${esc(a.details)}</p><small>${esc(a.duration)} • ${esc(a.price)}</small><br><button class="activity-toggle" data-id="${a.id}">+ Add to Enquiry</button></article>`).join("");
  $("#amenityGrid").innerHTML=data.amenities.map(a=>`<div class="amenity"><span>${a.icon}</span><strong>${esc(a.name)}</strong><small>${esc(a.text)}</small></div>`).join("");
  $("#galleryGrid").innerHTML=data.gallery.map(g=>`<button class="gallery-item"><img src="${g.src}" alt="${esc(g.alt)}" loading="lazy"></button>`).join("");
  const roomSelect=$("#roomType"); roomSelect.innerHTML=`<option value="Any available room">Any available room</option>`+data.rooms.filter(r=>r.available!==false).map(r=>`<option value="${esc(r.name)}">${esc(r.name)} — from ${formatINR(r.price)}</option>`).join("");
  const prices=data.rooms.filter(r=>r.available!==false).map(r=>Number(r.price)); $("#startingPrice").textContent=prices.length?`${formatINR(Math.min(...prices))}/night`:"Contact us";
  $("#contactName").textContent=data.contact.name;$("#contactLocation").textContent=data.contact.location;$("#contactPhone").textContent=data.contact.phone;
  if(data.contact.email){$("#emailWrap").hidden=false;$("#contactEmail").textContent=data.contact.email}
  $("#mapBtn").href=data.contact.mapUrl;$("#contactWhatsApp").href=wa("Hello Sea Turtle Stay! 👋 I would like to know more about your stay.");$("#floatingWhatsapp").href=wa("Hello Sea Turtle Stay! 👋 I would like to enquire about a stay.");
}
render();
const today=new Date().toISOString().split("T")[0];$("#checkin").min=today;$("#checkout").min=today;
$("#checkin").addEventListener("change",e=>{$("#checkout").min=e.target.value;if($("#checkout").value&&$("#checkout").value<=e.target.value)$("#checkout").value=""});
$("#booking").addEventListener("submit",e=>{e.preventDefault();const ci=$("#checkin").value,co=$("#checkout").value,gu=$("#guests").value,rc=$("#roomsCount").value,rt=$("#roomType").value;if(!ci||!co){alert("Please select both check-in and check-out dates.");return}if(new Date(co)<=new Date(ci)){alert("Check-out must be after check-in.");return}const acts=[...selectedActivities];const msg=`Hello Sea Turtle Stay! 👋\n\nI would like to enquire about a stay.\n\n📅 Check-in: ${ci}\n📅 Check-out: ${co}\n👥 Guests: ${gu}\n🛏️ Rooms: ${rc}\n🏡 Room Type: ${rt}\n🎯 Activities: ${acts.length?acts.join(", "):"None selected"}\n\nPlease share availability and the final price. Thank you!`;window.open(wa(msg),"_blank","noopener")});
document.addEventListener("click",e=>{const id=e.target.dataset.id;if(e.target.classList.contains("room-book")){const r=data.rooms.find(x=>x.id===id);$("#roomType").value=r.name;location.hash="#booking";$("#booking").scrollIntoView({behavior:"smooth",block:"center"});return}if(e.target.classList.contains("activity-toggle")){const a=data.activities.find(x=>x.id===id);if(selectedActivities.has(a.name))selectedActivities.delete(a.name);else selectedActivities.add(a.name);const card=e.target.closest(".activity");card.classList.toggle("selected");e.target.textContent=selectedActivities.has(a.name)?"✓ Added to Enquiry":" + Add to Enquiry"}if(e.target.closest(".gallery-item")){const img=e.target.closest(".gallery-item").querySelector("img");$("#lightbox img").src=img.src;$("#lightbox img").alt=img.alt;$("#lightbox").classList.add("open")}});
$("#lightbox").addEventListener("click",e=>{if(e.target===$("#lightbox")||e.target.classList.contains("close-lightbox"))$("#lightbox").classList.remove("open")});
$("#menuBtn").addEventListener("click",()=>$("#navLinks").classList.toggle("open"));$("#navLinks").addEventListener("click",e=>{if(e.target.tagName==="A")$("#navLinks").classList.remove("open")});$("#year").textContent=new Date().getFullYear();
